### ISSUE TITLE
Aimbot etc.

### ISSUE THREAD

**Issue by al1ksa** [vSylva/dying_light_hack#3]
Hello can you make aimbot more functional? like 
Which enemy will the aimbot target and legit aimbot or making smooth aimbot 
thanks for your work if u can do these things i appreciate you.

**Comment by vSylva** [comment]
Currently, I have not found a suitable method to build better aimbot

**Comment by akeyali** [comment]
well thanks i wanna learn coding but which one to choose i dont know should i start rust? or c++

**Comment by vSylva** [comment]
> well thanks i wanna learn coding but which one to choose i dont know should i start rust? or c++

For hack, it is more appropriate to learn c++ first, cuz many hacks are developed using c++

**Comment by akeyali** [comment]
thanks
